#!/bin/bash
position=$(playerctl metadata mpris:length --format '{{ duration(position) }}'| awk -F':' '{print ($1 * 60) + $2}' )
duration=$(playerctl metadata mpris:length)
durasec=$((duration/1000000))
# Convert position and duration to seconds

# Calculate the percentage
percentage=$(( (position * 100) / durasec ))

echo "$percentage"


