#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
killall swaync
/usr/libexec/xdg-desktop-portal-hyprland
sleep 2
systemctl --user restart swaync.service
